### ISSUE TITLE
Invalid value for Enum ... must be one of: - when trying to deserialize at merge-api/merge-hris-php/lib/ObjectSerializer.php:360

### ISSUE THREAD

**Issue by dbarbov1** [merge-api/merge-hris-php#12]
`InvalidArgumentException(code: 0): Invalid value for enum '\\MergeHRISClient\\Model\\MaritalStatusEnum', must be one of: 'SINGLE', 'MARRIED_FILING_JOINTLY', 'MARRIED_FILING_SEPARATELY', 'HEAD_OF_HOUSEHOLD', 'QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD' at /vendor/merge-api/merge-hris-php/lib/ObjectSerializer.php:360)"}  `
This happens when a deserialization is attempted into Enum classes, particularly when the values of the enum from the third party HRIS system are different.
![Screenshot 2022-11-16 at 16 06 35](https://user-images.githubusercontent.com/40503718/202201853-c8d4cad2-a703-45ae-a11b-ac1eb6ba46bf.png)
In your documentation it is said that values that are not matched against the possible values from your Enum classes should be let through.
![Screenshot 2022-11-16 at 16 07 09](https://user-images.githubusercontent.com/40503718/202202213-27328a9e-0f9e-4eca-8de9-07ea43068e37.png)

This is also known to happen in Employment::employment_status field type Enum
`{“exception”:“[object] (InvalidArgumentException(code: 0): Invalid value for enum ‘\\MergeHRISClient\\Model\\EmploymentTypeEnum’, must be one of: ‘FULL_TIME’, ‘PART_TIME’, ‘INTERN’, ‘CONTRACTOR’, ‘FREELANCE’ at /vendor/merge-api/merge-hris-php/lib/ObjectSerializer.php:360)“} `

Same for Groups:
`Invalid value for enum '\\MergeHRISClient\\Model\\GroupTypeEnum', must be one of: 'TEAM', 'DEPARTMENT', 'COST_CENTER', 'BUSINESS_UNIT' at /vendor/merge-api/merge-hris-php/lib/ObjectSerializer.php:360)"}`

**Comment by leewang0** [comment]
This should have been fixed in v1.0.4 (apologies for the malformed v1.0.3)
