### ISSUE TITLE
Duplicated declaration of method, resulting in compile error.

### ISSUE THREAD

**Issue by dilyan-barbov** [merge-api/merge-hris-php#7]
MergeHRISClient\Model\SyncStatus::getModelName() is declared twice, resulting in 
(1/1) FatalErrorException
Compile Error: Cannot redeclare MergeHRISClient\Model\SyncStatus::getModelName()

file -> lib/Model/SyncStatus.php

**Comment by leewang0** [comment]
Should have been fixed in v1.0.1
