### ISSUE TITLE
LocationsApi::locationsList() results in 500 ClassNotFound error

### ISSUE THREAD

**Issue by dbarbov1** [merge-api/merge-hris-php#9]
Attempted to load class "CountryEnum" from the global namespace.
Did you forget a "use" statement for "MergeHRISClient\Model\CountryEnum"? 
This happens when trying to call LocationsApi::locationsList()
<img width="770" alt="Screenshot 2022-10-31 at 12 29 15" src="https://user-images.githubusercontent.com/40503718/198988337-fd24d72d-a0b6-448e-b397-f5a14f03ae49.png">

**Comment by leewang0** [comment]
should be fixed in https://github.com/merge-api/merge-hris-php/pull/11
